package productflow

import "github.com/gin-gonic/gin"

func Register(g *gin.RouterGroup, h *Handler) {
	if g == nil || h == nil {
		return
	}
	g.GET("/source-products", h.ListSources)
	g.POST("/source-products", h.CreateSource)
	g.POST("/source-products/import", h.ImportSources)
	g.GET("/source-products/:id", h.GetSource)
	g.POST("/source-products/:id/candidate", h.CreateCandidate)
	g.GET("/candidates", h.ListCandidates)
	g.GET("/candidates/:id", h.GetCandidate)
	g.POST("/candidates/:id/analyze", h.AnalyzeCandidate)
	g.POST("/candidates/analyze-batch", h.CreateAnalysisBatch)
	g.POST("/candidates/bulk/:action", h.BulkCandidateAction)
	g.GET("/candidate-analysis-batches/:id", h.GetAnalysisBatch)
	g.GET("/candidate-analysis-batches", h.ListAnalysisBatches)
	g.GET("/candidate-analysis-batches/:id/items", h.ListAnalysisBatchItems)
	g.POST("/candidate-analysis-batches/:id/pause", h.PauseAnalysisBatch)
	g.POST("/candidate-analysis-batches/:id/resume", h.ResumeAnalysisBatch)
	g.POST("/candidate-analysis-batches/:id/cancel", h.CancelAnalysisBatch)
	g.POST("/candidate-analysis-batches/:id/retry-failed", h.RetryFailedAnalysisBatch)
	g.GET("/candidate-analysis-batches/:id/top", h.TopRecommendations)
	g.POST("/candidates/:id/market-signals", h.CreateMarketSignal)
	g.GET("/candidates/:id/market-signals", h.ListMarketSignals)
	g.POST("/market-signals/import", h.ImportMarketSignals)
	g.GET("/market-signal-providers/status", h.MarketSignalProviderStatuses)
	g.POST("/performance/import", h.ImportPerformance)
	g.GET("/performance", h.ListPerformance)
	g.GET("/performance/summary", h.PerformanceSummary)
	g.GET("/evaluation/selection-performance", h.SelectionPerformance)
	g.GET("/candidates/:id/analysis", h.LatestAnalysis)
	g.GET("/candidates/:id/analyses", h.ListAnalyses)
	g.POST("/candidates/:id/approve", h.ApproveCandidate)
	g.POST("/candidates/:id/reject", h.RejectCandidate)
	g.POST("/candidates/:id/watch", h.WatchCandidate)
	g.GET("/catalog-products", h.ListCatalog)
	g.GET("/catalog-products/:id", h.GetCatalog)
	g.POST("/catalog-products/:id/listing-drafts", h.CreateListingDraft)
	g.GET("/listing-drafts", h.ListListingDrafts)
	g.GET("/listing-drafts/:id", h.GetListingDraft)
	g.PUT("/listing-drafts/:id", h.UpdateListingDraft)
	g.POST("/listing-drafts/:id/recalculate", h.RecalculateListingDraft)
	g.DELETE("/listing-drafts/:id", h.DeleteListingDraft)
	g.GET("/cost-center", h.CostCenter)
	g.GET("/selection-dashboard", h.SelectionDashboard)
	g.GET("/pricing-profiles", h.ListPricingProfiles)
	g.POST("/pricing-profiles", h.CreatePricingProfile)
	g.PUT("/pricing-profiles/:id", h.UpdatePricingProfile)
	g.POST("/pricing-profiles/:id/copy", h.CopyPricingProfile)
	g.POST("/pricing-profiles/:id/default", h.SetDefaultPricingProfile)
	g.DELETE("/pricing-profiles/:id", h.DeletePricingProfile)
}
