import { ModalForm, ProFormSelect, ProFormText, ProTable } from '@ant-design/pro-components';
import { Alert, Button, Space, Tag, message } from 'antd';
import { useRef } from 'react';
import type { ActionType, ProColumns } from '@ant-design/pro-components';
import { TmPageContainer } from '@/components/ui';
import { controlMarketProvider, createMarketProviderConfig, fetchMarketProviderConfigs, healthCheckMarketProvider, type MarketProviderConfig } from '@/services/productFlow';

const sourceLabels: Record<string,string> = { official:'官方', authorized:'授权', public:'公开', manual:'人工', csv_import:'CSV 导入', fixture:'测试数据' };
export default function MarketProvidersPage(){const actionRef=useRef<ActionType>();const columns:ProColumns<MarketProviderConfig>[]=[{title:'Provider',dataIndex:'name'},{title:'平台',dataIndex:'platform'},{title:'来源等级',dataIndex:'sourceLevel',render:(_,row)=><Tag color={row.sourceLevel==='fixture'?'orange':'blue'}>{sourceLabels[row.sourceLevel]||row.sourceLevel}</Tag>},{title:'状态',dataIndex:'status',render:(_,row)=><Tag color={row.status==='healthy'?'green':row.status==='unhealthy'?'red':'default'}>{row.status}</Tag>},{title:'凭据',render:(_,row)=>row.credentialConfigured?<Tag color="green">已配置 {row.credentialHint}</Tag>:<Tag>未配置</Tag>},{title:'最后检查',dataIndex:'lastHealthCheckAt',valueType:'dateTime'},{title:'最后成功',dataIndex:'lastSuccessAt',valueType:'dateTime'},{title:'操作',valueType:'option',render:(_,row)=><Space wrap><Button size="small" onClick={()=>void healthCheckMarketProvider(row.id).then(()=>{message.success('健康检查完成');actionRef.current?.reload();})}>测试连接</Button><Button size="small" onClick={()=>void controlMarketProvider(row.id,row.enabled?'disable':'enable').then(()=>actionRef.current?.reload())}>{row.enabled?'禁用':'启用'}</Button>{row.lastError?<Button size="small" danger onClick={()=>message.error(row.lastError)}>查看错误</Button>:null}</Space>}];return <TmPageContainer title="Market Providers" subTitle="管理合法、授权、可追溯的市场数据来源"><Alert type="warning" showIcon message="当前没有已配置的真实网络 Provider。Official / Authorized 适配器不会伪造连接成功；凭据只接受环境变量引用。" style={{marginBottom:16}}/><ProTable<MarketProviderConfig> actionRef={actionRef} rowKey="id" search={false} columns={columns} request={async()=>{const data=await fetchMarketProviderConfigs();return{data:data.list,success:true,total:data.list.length}}} toolBarRender={()=>[<ModalForm key="create" title="配置 Provider" trigger={<Button type="primary">新增配置</Button>} onFinish={async(values)=>{await createMarketProviderConfig({...values,config:{}});message.success('配置已保存');actionRef.current?.reload();return true}}><ProFormText name="name" label="名称" rules={[{required:true}]}/><ProFormSelect name="providerType" label="Provider 类型" options={[{label:'Official / Authorized Placeholder',value:'official-placeholder'},{label:'人工录入',value:'manual'},{label:'CSV 导入',value:'csv_import'}]} rules={[{required:true}]}/><ProFormSelect name="platform" label="平台" options={[{label:'闲鱼',value:'xianyu'},{label:'淘宝',value:'taobao'}]} rules={[{required:true}]}/><ProFormSelect name="sourceLevel" label="来源等级" options={Object.entries(sourceLabels).map(([value,label])=>({value,label}))} rules={[{required:true}]}/><ProFormText name="credentialReference" label="凭据引用" placeholder="env:MARKET_PROVIDER_TOKEN" extra="不填写 Secret，只填写环境变量引用"/></ModalForm>]} /></TmPageContainer>}
