import { history, useParams } from '@umijs/max';
import { Alert, Button, Card, Col, Descriptions, Divider, Form, Input, InputNumber, List, Row, Space, Tag, Typography, message } from 'antd';
import { useEffect, useState } from 'react';
import { TmPageContainer } from '@/components/ui';
import { downloadPublishPackage, fetchListingContentVersions, fetchListingWorkspace, generateListingContent, generatePublishPackage, markListingPublishedManual, markListingReady, restoreListingContent, reviewListingContent, updateListingAssets, updateListingContent, updateListingDraft, type ListingContentVersion, type ListingWorkspace } from '@/services/productFlow';
import { money, percent } from '../shared';

const { Paragraph, Text } = Typography;
const copyText = async (value: string) => { try { await navigator.clipboard.writeText(value); message.success('已复制'); } catch { const area = document.createElement('textarea'); area.value = value; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove(); message.success('已复制'); } };

export default function ListingReviewPage() {
  const { id = '' } = useParams<{ id: string }>(); const [data, setData] = useState<ListingWorkspace>(); const [versions, setVersions] = useState<ListingContentVersion[]>([]); const [form] = Form.useForm();
  const load = async () => { const [next, historyRows] = await Promise.all([fetchListingWorkspace(id), fetchListingContentVersions(id)]); setData(next); setVersions(historyRows.list); form.setFieldsValue({ title: next.content?.title, description: next.content?.description, sellingPoints: next.content?.sellingPoints?.join('\n'), keywords: next.content?.keywords?.join('\n'), salePrice: next.listing.salePrice }); };
  useEffect(() => { void load(); }, [id]);
  if (!data) return <TmPageContainer title="内容审核"><Card loading /></TmPageContainer>;
  const content = data.content; const save = async () => { const v = await form.validateFields(); await updateListingContent(id, { title: v.title, description: v.description, sellingPoints: String(v.sellingPoints || '').split(/\r?\n/).filter(Boolean), keywords: String(v.keywords || '').split(/\r?\n/).filter(Boolean), faq: content?.faq || [] }); if (Number(v.salePrice) !== Number(data.listing.salePrice)) { await updateListingDraft(id, { salePrice: Number(v.salePrice) }); } await load(); message.success('内容已保存，售价与预计利润已重新计算'); };
  return <TmPageContainer title="内容审核" subTitle={`${data.listing.platform === 'xianyu' ? '闲鱼' : '淘宝'}版本 · 人工审核后才能进入可发布状态`} onBack={() => history.push('/listing-drafts')}>
    <Row gutter={[16, 16]}>
      <Col xs={24} xl={7}><Card title="原始商品信息"><Descriptions column={1} size="small"><Descriptions.Item label="标准标题">{data.catalog.title}</Descriptions.Item><Descriptions.Item label="供应商（内部）">{data.catalog.supplier || '待补充'}</Descriptions.Item><Descriptions.Item label="采购成本（内部）">{money(data.catalog.purchaseCost)}</Descriptions.Item><Descriptions.Item label="SKU">{data.catalog.skus?.map((v) => v.skuName).join(' / ') || '待补充'}</Descriptions.Item><Descriptions.Item label="图片">{data.assets.filter((v) => !v.excluded).length} / {data.assets.length} 张</Descriptions.Item></Descriptions><Alert style={{ marginTop: 16 }} type="info" showIcon message="供应商、货源链接和成本只用于内部运营，不会放入公开详情。" /><Divider /><Text strong>图片选择</Text><List size="small" dataSource={data.assets} locale={{ emptyText: '暂无图片' }} renderItem={(asset) => <List.Item actions={[<Button key="primary" type="link" disabled={asset.isPrimary || asset.excluded} onClick={() => updateListingAssets(id, data.assets.map((v) => ({ id: v.id, sortOrder: v.sortOrder, isPrimary: v.id === asset.id, excluded: v.excluded }))).then(load)}>设为主图</Button>, <Button key="exclude" type="link" onClick={() => updateListingAssets(id, data.assets.map((v) => ({ id: v.id, sortOrder: v.sortOrder, isPrimary: v.id === asset.id ? false : v.isPrimary, excluded: v.id === asset.id ? !v.excluded : v.excluded }))).then(load)}>{asset.excluded ? '恢复' : '排除'}</Button>]}><Text ellipsis style={{ maxWidth: 180 }}>{asset.sourceReference || asset.sourceUrl}</Text></List.Item>} /></Card></Col>
      <Col xs={24} xl={10}><Card title="平台内容" extra={<Space><Button onClick={() => generateListingContent(id, 'template_only').then(load)}>重新模板生成</Button><Button onClick={() => generateListingContent(id, 'ai_generate').then(load)}>重新 AI 生成</Button></Space>}>
        {!content && <Alert type="warning" showIcon message="尚未生成内容" />}
        <Form layout="vertical" form={form}><Form.Item name="title" label="标题" rules={[{ required: true }]}><Space.Compact style={{ width: '100%' }}><Input /><Button onClick={() => copyText(form.getFieldValue('title') || '')}>复制</Button></Space.Compact></Form.Item><Form.Item name="description" label="结构化详情" rules={[{ required: true }]}><Input.TextArea rows={9} /></Form.Item><Form.Item name="sellingPoints" label="卖点（每行一项）"><Input.TextArea rows={5} /></Form.Item><Form.Item name="keywords" label="已审核关键词（每行一项）"><Input.TextArea rows={3} /></Form.Item><Form.Item name="salePrice" label="平台售价"><Space.Compact><Button disabled>¥</Button><InputNumber min={0.01} precision={2} /></Space.Compact></Form.Item><Space wrap><Button type="primary" onClick={save}>保存并重算利润</Button><Button onClick={() => copyText(form.getFieldValue('description') || '')}>复制描述</Button><Button onClick={() => copyText(form.getFieldValue('sellingPoints') || '')}>复制卖点</Button><Button onClick={() => copyText(form.getFieldValue('keywords') || '')}>复制关键词</Button></Space></Form>
      </Card></Col>
      <Col xs={24} xl={7}><Card title="风险与利润"><Descriptions column={1} size="small"><Descriptions.Item label="预计售价">{money(data.listing.salePrice)}</Descriptions.Item><Descriptions.Item label="预计利润">{money(data.listing.estimatedProfit)}</Descriptions.Item><Descriptions.Item label="预计利润率">{percent(data.listing.estimatedMargin)}</Descriptions.Item><Descriptions.Item label="内容版本">{content ? `v${content.version} / ${content.promptVersion}` : '-'}</Descriptions.Item><Descriptions.Item label="AI状态">{content?.aiStatus || '-'}</Descriptions.Item></Descriptions><Divider />
        <Text strong>风险提示</Text><List size="small" dataSource={content?.warnings || []} locale={{ emptyText: '暂无 Warning' }} renderItem={(v) => <List.Item><Tag color="orange">Warning</Tag>{v}</List.Item>} /><List size="small" dataSource={content?.blockers || []} locale={{ emptyText: '暂无 Blocker' }} renderItem={(v) => <List.Item><Tag color="red">Blocker</Tag>{v}</List.Item>} />
        <Space direction="vertical" style={{ width: '100%', marginTop: 12 }}><Button block onClick={() => reviewListingContent(id, 'approve').then(load)}>人工批准内容</Button><Button block danger onClick={() => reviewListingContent(id, 'reject').then(load)}>退回</Button><Button block type="primary" onClick={() => markListingReady(id).then(load)}>完成发布前检查</Button><Button block onClick={async () => { await generatePublishPackage(id); await load(); message.success('发布包已生成，可在下方鉴权下载'); }}>生成发布包</Button></Space>
        <Divider /><Text strong>历史内容</Text><List size="small" dataSource={versions} locale={{ emptyText: '暂无历史版本' }} renderItem={(v) => <List.Item actions={[<Button key="restore" type="link" disabled={v.id === content?.id} onClick={() => restoreListingContent(id, v.id).then(load)}>恢复为新版本</Button>]}>v{v.version} · {v.promptVersion} · {v.reviewStatus}</List.Item>} />
        <Divider /><Text strong>发布包</Text>{data.packages.map((p) => <Paragraph key={p.id}><Button type="link" style={{ padding: 0 }} onClick={() => downloadPublishPackage(p.id, p.packageVersion)}>下载 package v{p.packageVersion}</Button> · {Math.ceil(p.sizeBytes / 1024)} KB</Paragraph>)}
        {data.listing.publishStatus === 'ready_to_publish' && <Form layout="vertical" onFinish={async (v) => { await markListingPublishedManual(id, v); await load(); message.success('已记录人工发布；未调用平台接口'); }}><Divider /><Form.Item name="platformListingId" label="平台商品 ID" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="listingUrl" label="商品链接"><Input /></Form.Item><Form.Item name="notes" label="备注"><Input.TextArea /></Form.Item><Button htmlType="submit">标记已人工发布</Button></Form>}
      </Card></Col>
    </Row>
  </TmPageContainer>;
}
