import { history, useParams } from '@umijs/max';
import { Alert, Button, Card, Col, Descriptions, Divider, Form, Input, InputNumber, List, Modal, Row, Select, Space, Switch, Tag, Typography, Upload, message } from 'antd';
import { useEffect, useState } from 'react';
import { TmPageContainer } from '@/components/ui';
import { createContentQualityReview, deleteListingAsset, downloadPublishPackage, fetchListingContentVersions, fetchListingWorkspace, generateListingContent, generatePublishPackage, markListingPublishedManual, markListingReady, restoreListingContent, reviewListingContent, updateListingAssets, updateListingContent, updateListingDraft, uploadListingAsset, viewListingAsset, type ListingContentVersion, type ListingWorkspace } from '@/services/productFlow';
import { money, percent } from '../shared';

const { Paragraph, Text } = Typography;
const copyText = async (value: string) => { try { await navigator.clipboard.writeText(value); } catch { const area = document.createElement('textarea'); area.value = value; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove(); } message.success('已复制'); };

export default function ListingReviewPage() {
  const { id = '' } = useParams<{ id: string }>(); const [data, setData] = useState<ListingWorkspace>(); const [versions, setVersions] = useState<ListingContentVersion[]>([]); const [preview, setPreview] = useState<string>(); const [form] = Form.useForm(); const [qualityForm] = Form.useForm();
  const load = async () => { const [next, historyRows] = await Promise.all([fetchListingWorkspace(id), fetchListingContentVersions(id)]); setData(next); setVersions(historyRows.list); form.setFieldsValue({ title: next.content?.title, description: next.content?.description, sellingPoints: next.content?.sellingPoints?.join('\n'), keywords: next.content?.keywords?.join('\n'), salePrice: next.listing.salePrice }); };
  useEffect(() => { void load(); }, [id]);
  if (!data) return <TmPageContainer title="内容审核"><Card loading /></TmPageContainer>;
  const content = data.content;
  const save = async () => { const v = await form.validateFields(); await updateListingContent(id, { title: v.title, description: v.description, sellingPoints: String(v.sellingPoints || '').split(/\r?\n/).filter(Boolean), keywords: String(v.keywords || '').split(/\r?\n/).filter(Boolean), faq: content?.faq || [] }); if (Number(v.salePrice) !== Number(data.listing.salePrice)) await updateListingDraft(id, { salePrice: Number(v.salePrice) }); await load(); message.success('内容已保存，售价变化已重新计算利润'); };
  const saveAssets = (transform: (index: number) => { sortOrder: number; isPrimary: boolean; excluded: boolean }) => updateListingAssets(id, data.assets.map((asset, index) => ({ id: asset.id, ...transform(index) }))).then(load);
  return <TmPageContainer title="内容审核" subTitle={`${data.listing.platform === 'xianyu' ? '闲鱼' : '淘宝'}版本 · 人工审核后才能生成发布资料包`} onBack={() => history.push('/listing-drafts')}>
    <Row gutter={[16, 16]}>
      <Col xs={24} xl={7}><Card title="商品与图片"><Descriptions column={1} size="small"><Descriptions.Item label="标准标题">{data.catalog.title}</Descriptions.Item><Descriptions.Item label="供应商（内部）">{data.catalog.supplier || '待补充'}</Descriptions.Item><Descriptions.Item label="采购成本（内部）">{money(data.catalog.purchaseCost)}</Descriptions.Item><Descriptions.Item label="SKU">{data.catalog.skus?.map((v) => v.skuName).join(' / ') || '待补充'}</Descriptions.Item></Descriptions><Alert style={{ marginTop: 16 }} type="info" showIcon message="供应商、货源链接和成本不会放入公开资料。" /><Divider /><Upload showUploadList={false} accept="image/jpeg,image/png,image/webp,image/gif" customRequest={async ({ file, onSuccess, onError }) => { try { await uploadListingAsset(id, file as File); onSuccess?.({}); await load(); } catch (e) { onError?.(e as Error); } }}><Button>上传本地图片</Button></Upload><List size="small" dataSource={data.assets} locale={{ emptyText: '暂无图片' }} renderItem={(asset, index) => <List.Item actions={[
        asset.cached && <a key="view" onClick={async () => { const blob = await viewListingAsset(asset.id); setPreview(URL.createObjectURL(blob)); }}>查看</a>,
        index > 0 && <a key="up" onClick={() => saveAssets((i) => ({ sortOrder: i === index ? index - 1 : i === index - 1 ? index : data.assets[i].sortOrder, isPrimary: data.assets[i].isPrimary, excluded: data.assets[i].excluded }))}>上移</a>,
        <a key="primary" onClick={() => saveAssets((i) => ({ sortOrder: data.assets[i].sortOrder, isPrimary: i === index, excluded: data.assets[i].excluded }))}>主图</a>,
        <a key="exclude" onClick={() => saveAssets((i) => ({ sortOrder: data.assets[i].sortOrder, isPrimary: i === index ? false : data.assets[i].isPrimary, excluded: i === index ? !asset.excluded : data.assets[i].excluded }))}>{asset.excluded ? '恢复' : '排除'}</a>,
        asset.sourceType === 'operator_upload' && <a key="delete" onClick={() => deleteListingAsset(id, asset.id).then(load)}>删除</a>,
      ].filter(Boolean)}><Space direction="vertical" size={0}><Text ellipsis style={{ maxWidth: 180 }}>{asset.sourceReference || asset.sourceUrl}</Text><Text type="secondary">{asset.sourceType === 'operator_upload' ? '运营者上传' : '货源原图'} · {asset.cached ? '已缓存' : '未缓存'}</Text></Space></List.Item>} /></Card></Col>
      <Col xs={24} xl={10}><Card title="平台内容" extra={<Space><Button onClick={() => generateListingContent(id, 'template_only').then(load)}>模板生成</Button><Button onClick={() => generateListingContent(id, 'ai_generate').then(load)}>AI 生成</Button></Space>}>{!content && <Alert type="warning" showIcon message="尚未生成内容" />}<Form layout="vertical" form={form}><Form.Item name="title" label="标题" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="description" label="详情" rules={[{ required: true }]}><Input.TextArea rows={9} /></Form.Item><Form.Item name="sellingPoints" label="卖点（每行一项）"><Input.TextArea rows={5} /></Form.Item><Form.Item name="keywords" label="关键词（每行一项）"><Input.TextArea rows={3} /></Form.Item><Form.Item name="salePrice" label="平台售价"><InputNumber min={0.01} precision={2} prefix="¥" /></Form.Item><Space wrap><Button type="primary" onClick={save}>保存并重算利润</Button><Button onClick={() => copyText(form.getFieldValue('title') || '')}>复制标题</Button><Button onClick={() => copyText(form.getFieldValue('description') || '')}>复制描述</Button></Space></Form></Card></Col>
      <Col xs={24} xl={7}><Card title="风险、利润与验收"><Descriptions column={1} size="small"><Descriptions.Item label="预计售价">{money(data.listing.salePrice)}</Descriptions.Item><Descriptions.Item label="预计利润">{money(data.listing.estimatedProfit)}</Descriptions.Item><Descriptions.Item label="预计利润率">{percent(data.listing.estimatedMargin)}</Descriptions.Item><Descriptions.Item label="AI 状态">{content?.aiStatus || '-'}</Descriptions.Item><Descriptions.Item label="Provider / 模型">{content?.modelProvider || '未调用'} / {content?.modelName || '-'}</Descriptions.Item><Descriptions.Item label="耗时 / Tokens">{content?.aiLatencyMs || 0} ms / {content?.aiInputTokens || 0}+{content?.aiOutputTokens || 0}</Descriptions.Item></Descriptions><Divider /><List size="small" dataSource={content?.warnings || []} locale={{ emptyText: '暂无 Warning' }} renderItem={(v) => <List.Item><Tag color="orange">Warning</Tag>{v}</List.Item>} /><List size="small" dataSource={content?.blockers || []} locale={{ emptyText: '暂无 Blocker' }} renderItem={(v) => <List.Item><Tag color="red">Blocker</Tag>{v}</List.Item>} />
        <Form form={qualityForm} layout="vertical" initialValues={{ status: 'approved', titleQuality: 80, descriptionQuality: 80, factAccuracy: 100, wasEdited: false }} onFinish={async (v) => { await createContentQualityReview(id, v); await load(); message.success('质量验收已记录'); }}><Form.Item name="status" label="内容质量结论"><Select options={[{value:'approved',label:'通过'},{value:'needs_edit',label:'需修改'},{value:'rejected',label:'拒绝'}]} /></Form.Item><Space><Form.Item name="titleQuality" label="标题"><InputNumber min={0} max={100} /></Form.Item><Form.Item name="descriptionQuality" label="描述"><InputNumber min={0} max={100} /></Form.Item><Form.Item name="factAccuracy" label="事实"><InputNumber min={0} max={100} /></Form.Item></Space><Form.Item name="wasEdited" label="人工修改" valuePropName="checked"><Switch /></Form.Item><Form.Item name="editReason" label="修改原因"><Input /></Form.Item><Button htmlType="submit">记录质量结果</Button></Form>
        <Divider /><Space direction="vertical" style={{ width: '100%' }}><Button block onClick={() => reviewListingContent(id, 'approve').then(load)}>人工批准内容</Button><Button block danger onClick={() => reviewListingContent(id, 'reject').then(load)}>退回</Button><Button block type="primary" onClick={() => markListingReady(id).then(load)}>完成发布前检查</Button><Button block onClick={async () => { await generatePublishPackage(id); await load(); message.success('发布包已生成'); }}>生成发布包</Button></Space><Divider />
        <Text strong>历史内容</Text><List size="small" dataSource={versions} renderItem={(v) => <List.Item actions={[<a key="restore" onClick={() => restoreListingContent(id, v.id).then(load)}>恢复</a>]}>v{v.version} · {v.promptVersion}</List.Item>} /><Text strong>发布包</Text>{data.packages.map((p) => <Paragraph key={p.id}><a onClick={() => downloadPublishPackage(p.id, p.packageVersion)}>下载 package v{p.packageVersion}</a> · {Math.ceil(p.sizeBytes / 1024)} KB</Paragraph>)}
        {data.listing.publishStatus === 'ready_to_publish' && <Form layout="vertical" onFinish={async (v) => { await markListingPublishedManual(id, v); await load(); }}><Form.Item name="platformListingId" label="平台商品 ID" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="listingUrl" label="商品链接"><Input /></Form.Item><Button htmlType="submit">标记已人工发布</Button></Form>}
      </Card></Col>
    </Row><Modal open={Boolean(preview)} footer={null} onCancel={() => { if (preview) URL.revokeObjectURL(preview); setPreview(undefined); }}>{preview && <img src={preview} alt="Listing 图片预览" style={{ width: '100%', maxHeight: '70vh', objectFit: 'contain' }} />}</Modal>
  </TmPageContainer>;
}
